# Generated by Django 3.2.8 on 2021-10-10 18:27

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.CharField(default=reports.models._get_random_transaction_id_str, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
