# Generated by Django 3.2.8 on 2021-10-10 18:29

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='generated_report',
            field=models.FilePathField(blank=True, match='.pdf', null=True, path=pathlib.PurePosixPath('/home/tornike/Desktop/demos/notarify_demos/demo/PDF_Reports')),
        ),
    ]
