# Generated by Django 3.2.8 on 2021-10-10 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_generated_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='role',
            new_name='country',
        ),
    ]
