# Generated by Django 3.2.8 on 2021-10-11 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_role_report_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='generated_report',
        ),
    ]
